import type { Icon } from "@phosphor-icons/react";
import {
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowsClockwiseIcon,
  BuildingsIcon,
  CalendarBlankIcon,
  CalendarDotsIcon,
  CaretDownIcon,
  CheckCircleIcon,
  ClipboardTextIcon,
  ClockIcon,
  DatabaseIcon,
  EyeIcon,
  GitCommitIcon,
  GithubLogoIcon,
  GlobeHemisphereWestIcon,
  LinkSimpleIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MoonIcon,
  PlayCircleIcon,
  ShieldCheckIcon,
  StopIcon,
  SunIcon,
  UserIcon,
  XIcon,
} from "@phosphor-icons/react";
import type { SemanticReferenceKind } from "../data/semantic-reference";

export const iconForSemanticReference: Record<SemanticReferenceKind, Icon> = {
  calendar_event: CalendarBlankIcon,
  deadline: CalendarDotsIcon,
  date_range: CalendarBlankIcon,
  source_time: ClockIcon,
  recurrence: ArrowsClockwiseIcon,
  person: UserIcon,
  organization: BuildingsIcon,
  location: MapPinIcon,
  source: DatabaseIcon,
  evidence: ClipboardTextIcon,
  proof: ShieldCheckIcon,
  repository: GithubLogoIcon,
  commit: GitCommitIcon,
  task: ClipboardTextIcon,
  run: PlayCircleIcon,
  graph_entity: GlobeHemisphereWestIcon,
  route: LinkSimpleIcon,
};

export {
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowsClockwiseIcon,
  CaretDownIcon,
  CheckCircleIcon,
  ClockIcon,
  DatabaseIcon,
  EyeIcon,
  MagnifyingGlassIcon,
  MoonIcon,
  StopIcon,
  SunIcon,
  XIcon,
};
