import type { AdminKnowledgeCard } from "./types";

export const fixtureKnowledgeCards: AdminKnowledgeCard[] = [
  {
    card_id: "knowledge-brain-life-record",
    entity_ref: "system:brain",
    domain: "life",
    kind: "system",
    title: "Brain life record",
    summary:
      "Append-only life telemetry and curated People, Projects, Moments, Daily, Eras, and Wiki knowledge. Brain is the durable source data plane; derived indexes must remain rebuildable from it.",
    source_system: "brain",
    source_locator: "brain://vault",
    source_native_id: "anipotts/brain",
    canonical_host: "ap-mini",
    canonical_path: null,
    sensitivity: "intimate",
    reveal_policy: "pointer_only",
    freshness_state: "unknown",
    observed_at: null,
    stale_after_seconds: 900,
    content_hash: "git:ac39e829",
    proof_refs: [
      "git:anipotts/brain/main/ac39e829",
      "local:/Users/anipotts/Projects/brain",
      "runtime:ap-mini-observation-unavailable",
    ],
    lineage_refs: [
      "knowport",
      "chatpack",
      "ani-os",
      "brain",
      "memory-lakehouse-frozen-analytics",
    ],
    related_card_ids: [
      "knowledge-rudy-query-interface",
      "knowledge-admin-life-inbox",
      "knowledge-memory-analytics",
    ],
    retrieval_instructions:
      "Query the Brain or Rudy read adapter by entity and time range. If Mini cannot be observed, use the Pro read mirror and label the answer as potentially stale.",
    context_budget_tokens: 320,
    event_refs: [],
    indexed_at: "2026-07-23T23:00:00.000Z",
  },
  {
    card_id: "knowledge-rudy-query-interface",
    entity_ref: "system:rudy",
    domain: "life",
    kind: "system",
    title: "Rudy retrieval interface",
    summary:
      "Regenerable query and materialized-view layer over Brain for people, history, relationships, messages, and cross-source context. Rudy is an interface and cache, not irreplaceable truth.",
    source_system: "rudy",
    source_locator: "rudy://knowledge",
    source_native_id: "anipotts/rudy",
    canonical_host: "ap-mini",
    canonical_path: "/Users/anipotts/Projects/rudy",
    sensitivity: "intimate",
    reveal_policy: "pointer_only",
    freshness_state: "unknown",
    observed_at: null,
    stale_after_seconds: 300,
    content_hash: "registry:rudy-runtime",
    proof_refs: ["infra:registries/project-boundaries.yml"],
    lineage_refs: ["brain://vault"],
    related_card_ids: [
      "knowledge-brain-life-record",
      "knowledge-admin-life-inbox",
    ],
    retrieval_instructions:
      "Use the existing Rudy read-only MCP or local query surface. Fall back to Brain when a materialized view is missing, stale, or contradictory.",
    context_budget_tokens: 260,
    event_refs: [],
    indexed_at: "2026-07-23T23:00:00.000Z",
  },
  {
    card_id: "knowledge-memory-analytics",
    entity_ref: "system:memory-lakehouse",
    domain: "life",
    kind: "system",
    title: "Memory and Lakehouse analytics",
    summary:
      "Frozen analytical program over Brain covering raw, bronze, silver, gold, graph, schedule, and insight designs. It remains prior art and future analytics, not a competing live source.",
    source_system: "infra-memory",
    source_locator: "infra://memory",
    source_native_id: null,
    canonical_host: "ap-pro",
    canonical_path: "/Users/anipotts/Infra/memory",
    sensitivity: "restricted",
    reveal_policy: "summary",
    freshness_state: "stale",
    observed_at: "2026-06-16T00:00:00.000Z",
    stale_after_seconds: null,
    content_hash: "doc:2026-06-16-chief-lineage-delta",
    proof_refs: [
      "infra:docs/2026-05-20-vision-plan.md",
      "infra:handoffs/2026-06-16-chief-lineage-delta.md",
    ],
    lineage_refs: ["lakehouse", "memory", "brain"],
    related_card_ids: ["knowledge-brain-life-record"],
    retrieval_instructions:
      "Read for analytical schemas, access rules, and prior decisions. Do not treat unfinished collectors or derived views as current life truth.",
    context_budget_tokens: 300,
    event_refs: [],
    indexed_at: "2026-07-23T23:00:00.000Z",
  },
  {
    card_id: "knowledge-admin-life-inbox",
    entity_ref: "project:admin-home",
    domain: "system",
    kind: "project",
    title: "Admin life inbox and knowledge gateway",
    summary:
      "Authenticated human interface for one global attention Inbox, searchable outcomes and history, and small knowledge cards that point to canonical evidence without copying full private histories.",
    source_system: "anipotts-com",
    source_locator: "admin://home",
    source_native_id: "entity-admin-home-lifecycle",
    canonical_host: "cloud",
    canonical_path: "/Users/anipotts/Code/projects/anipotts-com",
    sensitivity: "restricted",
    reveal_policy: "summary",
    freshness_state: "partial",
    observed_at: "2026-07-23T23:00:00.000Z",
    stale_after_seconds: 3600,
    content_hash: "git:8bc63265",
    proof_refs: [
      "git:branch/codex-pro-admin-home-lifecycle-2026-07-22",
      "handoff:2026-07-22-admin-home-conversation-lifecycle",
    ],
    lineage_refs: ["admin-pr-244", "admin-home-lifecycle"],
    related_card_ids: [
      "knowledge-brain-life-record",
      "knowledge-agent-work-history",
      "knowledge-infra-fleet",
    ],
    retrieval_instructions:
      "Use the authenticated Knowledge UI, read-only API, or admin MCP. Inbox results are attention only; search results remain reference cards.",
    context_budget_tokens: 280,
    event_refs: ["evt-admin-contract-2026-07-02"],
    indexed_at: "2026-07-23T23:00:00.000Z",
  },
  {
    card_id: "knowledge-agent-work-history",
    entity_ref: "system:agent-work-history",
    domain: "work",
    kind: "system",
    title: "Codex and Claude work history",
    summary:
      "Native Codex tasks, Claude sessions, handoffs, repositories, goals, statuses, and lineage remain on their originating machines. Admin stores bounded metadata and source locators.",
    source_system: "agent-runtimes",
    source_locator: "agents://tasks",
    source_native_id: null,
    canonical_host: "none",
    canonical_path: null,
    sensitivity: "restricted",
    reveal_policy: "pointer_only",
    freshness_state: "partial",
    observed_at: "2026-07-23T23:00:00.000Z",
    stale_after_seconds: 300,
    content_hash: "contract:work-lifecycle-v1",
    proof_refs: ["admin://work-lifecycle"],
    lineage_refs: ["codex", "claude-code", "infra-handoffs"],
    related_card_ids: ["knowledge-admin-life-inbox", "knowledge-infra-fleet"],
    retrieval_instructions:
      "Search bounded lifecycle metadata first, then retrieve the native task or session by host and native id. Never infer runtime activity from transcript recency.",
    context_budget_tokens: 300,
    event_refs: [],
    indexed_at: "2026-07-23T23:00:00.000Z",
  },
  {
    card_id: "knowledge-infra-fleet",
    entity_ref: "system:infra",
    domain: "fleet",
    kind: "system",
    title: "Infra and fleet truth",
    summary:
      "Git-backed machine, service, authority, capability, handoff, project, and runtime policy. Pro is the source and human workbench; Mini is the always-on runtime and durable retrieval host.",
    source_system: "infra",
    source_locator: "infra://",
    source_native_id: "anipotts/Infra",
    canonical_host: "ap-pro",
    canonical_path: "/Users/anipotts/Infra",
    sensitivity: "restricted",
    reveal_policy: "summary",
    freshness_state: "partial",
    observed_at: "2026-07-23T23:00:00.000Z",
    stale_after_seconds: 900,
    content_hash: "git:31a8a03+dirty-preserved",
    proof_refs: [
      "infra:machines/fleet.yml",
      "infra:registries/projects.yml",
      "infra:coord/authority.jsonl",
    ],
    lineage_refs: ["github:anipotts/Infra/main"],
    related_card_ids: [
      "knowledge-admin-life-inbox",
      "knowledge-agent-work-history",
      "knowledge-brain-life-record",
    ],
    retrieval_instructions:
      "Read committed policy and named registries, then verify live machine state. Dirty checkouts and generated registries are preservation boundaries, not automatic truth.",
    context_budget_tokens: 300,
    event_refs: ["evt-admin-contract-2026-07-02"],
    indexed_at: "2026-07-23T23:00:00.000Z",
  },
  {
    card_id: "knowledge-brand-content",
    entity_ref: "domain:brand-content",
    domain: "content",
    kind: "system",
    title: "Brand and content record",
    summary:
      "Brand deal truth, source assets, writing, newsletter, videos, text posts, images, carousels, social messages, acknowledgements, and publishing proof remain source-backed and owner-routed.",
    source_system: "brand-and-media",
    source_locator: "brand://",
    source_native_id: null,
    canonical_host: "ap-pro",
    canonical_path: "/Users/anipotts/Brand",
    sensitivity: "restricted",
    reveal_policy: "summary",
    freshness_state: "partial",
    observed_at: "2026-07-23T23:00:00.000Z",
    stale_after_seconds: 3600,
    content_hash: "registry:brand-content",
    proof_refs: ["local:/Users/anipotts/Brand", "local:/Users/anipotts/Media"],
    lineage_refs: ["chief/brand", "site/writing"],
    related_card_ids: ["knowledge-admin-life-inbox"],
    retrieval_instructions:
      "Retrieve the exact deal, piece, source asset, sent proof, acknowledgement, or platform locator. Do not treat exports or previews as publishing proof.",
    context_budget_tokens: 280,
    event_refs: [],
    indexed_at: "2026-07-23T23:00:00.000Z",
  },
  {
    card_id: "knowledge-jobs-career",
    entity_ref: "domain:jobs",
    domain: "work",
    kind: "system",
    title: "Jobs and career record",
    summary:
      "Role research, application materials, interview preparation, outreach, submissions, and employer evidence live in the durable Jobs project with provider actions kept separately gated.",
    source_system: "jobs",
    source_locator: "jobs://",
    source_native_id: "anipotts/jobs",
    canonical_host: "ap-pro",
    canonical_path: "/Users/anipotts/Personal/jobs",
    sensitivity: "restricted",
    reveal_policy: "summary",
    freshness_state: "partial",
    observed_at: "2026-07-23T23:00:00.000Z",
    stale_after_seconds: 3600,
    content_hash: "registry:jobs",
    proof_refs: ["local:/Users/anipotts/Personal/jobs"],
    lineage_refs: ["chief/jobs"],
    related_card_ids: ["knowledge-agent-work-history"],
    retrieval_instructions:
      "Search the Jobs project and bounded agent lineage. Verify applications, replies, and identity surfaces from their exact providers before claiming real-world completion.",
    context_budget_tokens: 260,
    event_refs: [],
    indexed_at: "2026-07-23T23:00:00.000Z",
  },
  {
    card_id: "knowledge-nyu-coursework",
    entity_ref: "domain:nyu",
    domain: "work",
    kind: "system",
    title: "NYU coursework record",
    summary:
      "Course materials, shared and private documents, deadlines, submissions, grades, and account-sunset evidence. Authenticated course state expires and must be refreshed before decisions.",
    source_system: "nyu",
    source_locator: "nyu://",
    source_native_id: null,
    canonical_host: "provider",
    canonical_path: "/Users/anipotts/Organizations/nyu",
    sensitivity: "restricted",
    reveal_policy: "human_present",
    freshness_state: "partial",
    observed_at: "2026-07-23T23:00:00.000Z",
    stale_after_seconds: 900,
    content_hash: "registry:nyu",
    proof_refs: ["local:/Users/anipotts/Organizations/nyu"],
    lineage_refs: ["chief/enviro"],
    related_card_ids: ["knowledge-agent-work-history"],
    retrieval_instructions:
      "Read local course artifacts, then refresh Brightspace or Drive when the answer depends on deadlines, submissions, grades, or document state.",
    context_budget_tokens: 280,
    event_refs: [],
    indexed_at: "2026-07-23T23:00:00.000Z",
  },
  {
    card_id: "knowledge-health-status",
    entity_ref: "domain:health",
    domain: "life",
    kind: "system",
    title: "Health status and vitals",
    summary:
      "Status-only health visibility and source pointers. Measurements do not create inferred tasks; care actions enter Inbox only when Ani or a verified source creates a real obligation.",
    source_system: "vitals",
    source_locator: "vitals://health",
    source_native_id: null,
    canonical_host: "ap-mini",
    canonical_path: "/Users/anipotts/Code/projects/vitals",
    sensitivity: "intimate",
    reveal_policy: "human_present",
    freshness_state: "unknown",
    observed_at: null,
    stale_after_seconds: 3600,
    content_hash: "registry:vitals",
    proof_refs: ["service:com.anipotts.vitals-api"],
    lineage_refs: ["memory-health-view"],
    related_card_ids: ["knowledge-brain-life-record"],
    retrieval_instructions:
      "Use the authorized health view only when required. Return status and source freshness, not raw measurements, unless the current task has explicit health-data authority.",
    context_budget_tokens: 220,
    event_refs: [],
    indexed_at: "2026-07-23T23:00:00.000Z",
  },
  {
    card_id: "knowledge-manual-capture",
    entity_ref: "system:manual-capture",
    domain: "life",
    kind: "system",
    title: "Notes and reminders capture",
    summary:
      "Apple Notes Personal is the low-friction writing origin and Apple Reminders is the simple action surface. Admin may point to both without becoming a second notes or task database.",
    source_system: "apple-personal",
    source_locator: "apple://personal",
    source_native_id: null,
    canonical_host: "provider",
    canonical_path: null,
    sensitivity: "intimate",
    reveal_policy: "human_present",
    freshness_state: "unknown",
    observed_at: null,
    stale_after_seconds: 900,
    content_hash: "policy:notes-reminders",
    proof_refs: ["handoff:2026-06-13-notes-reminders-cleanup"],
    lineage_refs: ["apple-notes", "apple-reminders"],
    related_card_ids: ["knowledge-brain-life-record"],
    retrieval_instructions:
      "Open the user-session Notes or Reminders source when current text matters. Background agents may use sanitized pointers only unless a reviewed adapter exists.",
    context_budget_tokens: 240,
    event_refs: ["evt-notes-user-session-2026-07-02"],
    indexed_at: "2026-07-23T23:00:00.000Z",
  },
  {
    card_id: "knowledge-finance-context",
    entity_ref: "domain:finance",
    domain: "life",
    kind: "system",
    title: "Finance context boundary",
    summary:
      "Current balances, transactions, and financial decisions remain in their exact provider or approved finance surface. Local systems retain metadata, reconciliation pointers, and proof only.",
    source_system: "finance-providers",
    source_locator: "finance://provider-context",
    source_native_id: null,
    canonical_host: "provider",
    canonical_path: "/Users/anipotts/Business",
    sensitivity: "intimate",
    reveal_policy: "human_present",
    freshness_state: "unknown",
    observed_at: null,
    stale_after_seconds: 300,
    content_hash: "policy:finance-boundary",
    proof_refs: ["infra:docs/life-systems-source-of-truth.md"],
    lineage_refs: ["business", "mercury", "wave"],
    related_card_ids: ["knowledge-admin-life-inbox"],
    retrieval_instructions:
      "Use exact provider or connected finance evidence for current state. Never infer payment, balances, or transactions from local reminders or historical summaries.",
    context_budget_tokens: 220,
    event_refs: [],
    indexed_at: "2026-07-23T23:00:00.000Z",
  },
];
