import {
  ADMIN_EVENT_SCHEMA_VERSION,
  type AdminCapabilityState,
  type AdminControlContracts,
  type AdminControlProjections,
  type AdminDeployState,
  type AdminEventEnvelope,
  type AdminFleetStatus,
  type AdminInboxItem,
  type AdminPieceState,
  type AdminProjectState,
  type AdminServiceRegistryViewItem,
  type AdminTaskLineage,
  type AdminTaskState,
} from "./types";
import {
  buildSentMailAwareness,
  buildSentMailMetadata,
  gmailSentDedupeKey,
} from "./sent-mail";

const NOW = "2026-07-02T16:45:00.000Z";
const RAYBAN_SENT_AT = "2026-07-08T00:00:00.000Z";
const PERSONAL_SYSTEM_CLEANUP_AT = "2026-07-15T16:00:00.000Z";
const PERSONAL_SYSTEM_CLEANUP_EVENT_ID =
  "evt-personal-system-cleanup-audit-2026-07-15";
const PERSONAL_SYSTEM_CLEANUP_TASK_ID = "task-personal-system-cleanup-current";

const raybanSentMail = buildSentMailMetadata({
  account: "hello@anipotts.com",
  sent_ref: "rayban-30-day-analytics-2026-07-08",
  subject: "Ray-Ban 30-day analytics",
  sent_at: RAYBAN_SENT_AT,
  has_attachments: "unknown",
  href: "metadata://gmail/sent/rayban-30-day-analytics-2026-07-08",
});

const raybanSentAwareness = buildSentMailAwareness(raybanSentMail, {
  completed: true,
  dedupe_key: gmailSentDedupeKey("rayban-30-day-analytics-2026-07-08"),
  event_id: "evt-gmail-sent-rayban-30-day-analytics-2026-07-08",
  privacy: "private",
});

const raybanPaymentFollowUp = buildSentMailAwareness(raybanSentMail, {
  completed: true,
  dedupe_key: gmailSentDedupeKey("rayban-30-day-analytics-2026-07-08"),
  event_id: "evt-gmail-sent-rayban-30-day-analytics-2026-07-08",
  privacy: "private",
  follow_up: {
    id: "inbox-rayban-payment-followup",
    dedupe_key: "brand:rayban-meta:payment-followup:2026-07-09",
    kind: "payment",
    title: "ray-ban payment follow-up",
    summary:
      "30-day sent mail and acknowledgement are proof; payment follow-up stays separate.",
    owner: "chief/brand",
    domain: "brand",
    entity_ref: "brand-deal:rayban-meta",
    attention_kind: "verification",
    urgency: "normal",
    status: "waiting_payment_proof",
    href: raybanSentMail.href,
    last_seen_at: "2026-07-09T00:00:00.000Z",
  },
});

export const adminControlContracts: AdminControlContracts = {
  event_fields: [
    "schema_version",
    "event_id",
    "dedupe_key",
    "source",
    "provider",
    "account",
    "actor",
    "kind",
    "ts",
    "privacy",
    "title",
    "summary",
    "href",
    "payload_ref",
    "created_by",
  ],
  inbox_card_fields: [
    "item_id",
    "dedupe_key",
    "event_refs",
    "domain",
    "entity_ref",
    "attention_kind",
    "source",
    "account",
    "title",
    "summary",
    "href",
    "status",
    "urgency",
    "owner",
    "action_kind",
    "expires_at",
    "last_seen_at",
  ],
  project_state_fields: [
    "project_id",
    "dedupe_key",
    "project_key",
    "display_name",
    "domain",
    "entity_ref",
    "owner_chief",
    "repository",
    "canonical_remote",
    "pro_path",
    "mini_path",
    "canonical_host_role",
    "lifecycle",
    "attention_kind",
    "last_observed_at",
    "agent_source",
    "event_refs",
    "task_refs",
  ],
  task_state_fields: [
    "task_id",
    "dedupe_key",
    "native_thread_id",
    "machine",
    "host",
    "project_ref",
    "cwd",
    "goal",
    "current_summary",
    "final_summary",
    "next_action",
    "proof_refs",
    "lifecycle",
    "attention_kind",
    "native_runtime_status",
    "created_at",
    "updated_at",
    "completed_at",
    "agent_source",
    "event_refs",
    "blocked_by",
  ],
  task_lineage_fields: [
    "lineage_id",
    "lineage_group_id",
    "task_ref",
    "parent_task_ref",
    "root_task_ref",
    "relation",
    "controller_ref",
    "agent_source",
    "event_refs",
    "updated_at",
  ],
  sent_mail_metadata_fields: [
    "account",
    "sent_ref",
    "subject",
    "sent_at",
    "has_attachments",
    "href",
  ],
  sent_mail_card_policy: {
    dedupe: "gmail-message-id-derived-ref",
    completed_obligation: "event-only",
    followups: "separate-inbox-items",
    sync: "refresh-on-open-plus-light-polling",
    raw_identifiers: "omitted",
    preview_text: "omitted",
  },
  piece_states: [
    "idea",
    "draft",
    "review",
    "export-ready",
    "publish-ready",
    "published",
    "archived",
  ],
  legal_piece_cycles: ["review -> draft", "published -> draft"],
};

export const fixtureEvents: AdminEventEnvelope[] = [
  {
    schema_version: ADMIN_EVENT_SCHEMA_VERSION,
    event_id: "evt-admin-contract-2026-07-02",
    dedupe_key: "admin:review:event-api-mcp-contract:2026-07-02",
    source: "fleet",
    provider: "admin",
    account: "admin.anipotts.com",
    actor: "codex",
    kind: "review.required",
    ts: NOW,
    privacy: "internal",
    title: "review event contract and read-only mcp",
    summary:
      "first review must cover event fields, projection api, mcp shape, retention, and inbox bento.",
    href: "/api/admin/projections",
    payload_ref: "r2://admin-event-payloads/2026/07/02/admin-contract.json",
    created_by: "codex",
  },
  raybanSentAwareness.event,
  {
    schema_version: ADMIN_EVENT_SCHEMA_VERSION,
    event_id: "evt-rayban-analytics-2026-07-02",
    dedupe_key: "brand:rayban-meta:analytics-reminder:2026-07-02",
    source: "brand",
    provider: "manual",
    account: "ray-ban meta",
    actor: "ani",
    kind: "deadline",
    ts: NOW,
    privacy: "private",
    title: "ray-ban analytics reminder",
    summary:
      "submit the 30-day analytics reminder so the deal closeout can move toward payment.",
    href: null,
    payload_ref: "r2://admin-event-payloads/2026/07/02/rayban-analytics.json",
    created_by: "codex",
  },
  {
    schema_version: ADMIN_EVENT_SCHEMA_VERSION,
    event_id: "evt-connect-topology-diff-2026-07-02",
    dedupe_key: "infra:connect:topology-diff:2026-07-02",
    source: "fleet",
    provider: "1password-connect",
    account: "agent-runtime",
    actor: "codex",
    kind: "approval.required",
    ts: NOW,
    privacy: "sensitive",
    title: "sign connect topology diff",
    summary:
      "value-serving and mcp write tools stay off until Ani signs the exact rule diff.",
    href: "/fleet",
    payload_ref:
      "r2://admin-event-payloads/2026/07/02/connect-topology-diff.json",
    created_by: "codex",
  },
  {
    schema_version: ADMIN_EVENT_SCHEMA_VERSION,
    event_id: "evt-notes-user-session-2026-07-02",
    dedupe_key: "notes:user-session-reader:todo-date:2026-07-02",
    source: "notes",
    provider: "apple-notes",
    account: "ap-pro",
    actor: "claude",
    kind: "adapter.scope",
    ts: NOW,
    privacy: "private",
    title: "daily notes reader stays user-session only",
    summary:
      "todo note import can read in a user session, never from launchd or background op.",
    href: null,
    payload_ref: "r2://admin-event-payloads/2026/07/02/notes-user-session.json",
    created_by: "codex",
  },
  {
    schema_version: ADMIN_EVENT_SCHEMA_VERSION,
    event_id: "evt-site-jobs-migration-2026-07-15",
    dedupe_key: "fleet:task-migration:site-jobs:2026-07-15",
    source: "fleet",
    provider: "codex",
    account: "admin.anipotts.com",
    actor: "codex",
    kind: "task.migrated",
    ts: "2026-07-15T15:00:00.000Z",
    privacy: "internal",
    title: "site jobs task migration reconciled",
    summary:
      "synthetic fixture links source task, controller worktree task, and destination task without raw execution payloads.",
    href: "/api/admin/task-lineage?task_id=task-site-jobs-destination",
    payload_ref: null,
    created_by: "codex",
  },
  {
    schema_version: ADMIN_EVENT_SCHEMA_VERSION,
    event_id: PERSONAL_SYSTEM_CLEANUP_EVENT_ID,
    dedupe_key: "fleet:personal-system-cleanup:audit:2026-07-15",
    source: "fleet",
    provider: "audit",
    account: "ap-mini",
    actor: "fleet/boss",
    kind: "audit.verified",
    ts: PERSONAL_SYSTEM_CLEANUP_AT,
    privacy: "internal",
    title: "personal system cleanup audit verified",
    summary:
      "metadata-only audit records durable roots, host roles, migration exceptions, and cleanup routing without moving files.",
    href: "/fleet",
    payload_ref: null,
    created_by: "codex",
  },
];

export const fixtureInboxItems: AdminInboxItem[] = [
  {
    item_id: "inbox-admin-contract-review",
    dedupe_key: "admin:review:event-api-mcp-contract:2026-07-02",
    event_refs: ["evt-admin-contract-2026-07-02"],
    domain: "admin",
    entity_ref: "admin-control:event-api-mcp-contract",
    attention_kind: "review",
    source: "fleet",
    account: "admin.anipotts.com",
    title: "review api plus mcp contract",
    summary:
      "event schema, projection api, read-only mcp, retention, and inbox bento move together.",
    href: "/api/admin/projections",
    status: "review",
    urgency: "urgent",
    owner: "codex chief",
    action_kind: "review",
    expires_at: null,
    last_seen_at: null,
  },
  raybanPaymentFollowUp.inbox_item!,
  {
    item_id: "inbox-connect-topology",
    dedupe_key: "infra:connect:topology-diff:2026-07-02",
    event_refs: ["evt-connect-topology-diff-2026-07-02"],
    domain: "infra",
    entity_ref: "onepassword-connect:agent-runtime",
    attention_kind: "approval",
    source: "fleet",
    account: "agent-runtime",
    title: "connect diff before value access",
    summary:
      "personal/business value-serving stays off; only the signed diff can open that lane.",
    href: "/fleet",
    status: "action required",
    urgency: "high",
    owner: "codex chief",
    action_kind: "approve",
    expires_at: null,
    last_seen_at: null,
  },
  {
    item_id: "inbox-notes-session-reader",
    dedupe_key: "notes:user-session-reader:todo-date:2026-07-02",
    event_refs: ["evt-notes-user-session-2026-07-02"],
    domain: "life",
    entity_ref: "notes:daily-todo-reader",
    attention_kind: "verification",
    source: "notes",
    account: "ap-pro",
    title: "notes import is user-session only",
    summary:
      "daily todo notes can enter inbox through the session reader, never a launchd reader.",
    href: null,
    status: "scoped",
    urgency: "normal",
    owner: "claude",
    action_kind: "verify",
    expires_at: null,
    last_seen_at: null,
  },
];

type PersonalCleanupProjectInput = {
  project_id: string;
  project_key: string;
  display_name: string;
  domain?: string;
  entity_ref: string;
  owner_chief?: string;
  repository?: string | null;
  canonical_remote?: string | null;
  pro_path?: string | null;
  mini_path?: string | null;
  canonical_host_role: string;
  lifecycle?: string;
};

function personalCleanupProject(
  input: PersonalCleanupProjectInput,
): AdminProjectState {
  return {
    project_id: input.project_id,
    dedupe_key: `project:${input.project_key}`,
    project_key: input.project_key,
    display_name: input.display_name,
    domain: input.domain ?? "work",
    entity_ref: input.entity_ref,
    owner_chief: input.owner_chief ?? "fleet/boss",
    repository: input.repository ?? null,
    canonical_remote: input.canonical_remote ?? null,
    pro_path: input.pro_path ?? null,
    mini_path: input.mini_path ?? null,
    canonical_host_role: input.canonical_host_role,
    lifecycle: input.lifecycle ?? "active",
    attention_kind: "review",
    last_observed_at: PERSONAL_SYSTEM_CLEANUP_AT,
    agent_source: "codex",
    event_refs: [PERSONAL_SYSTEM_CLEANUP_EVENT_ID],
    task_refs: [PERSONAL_SYSTEM_CLEANUP_TASK_ID],
  };
}

const personalSystemCleanupProjectStates: AdminProjectState[] = [
  personalCleanupProject({
    project_id: "project-pro-projects-brain",
    project_key: "pro-projects-brain",
    display_name: "brain",
    entity_ref: "audit:brain-parity-mismatch",
    pro_path: "/Users/anipotts/Projects/brain",
    canonical_host_role: "source",
  }),
  personalCleanupProject({
    project_id: "project-pro-projects-claudeface",
    project_key: "pro-projects-claudeface",
    display_name: "claudeface",
    entity_ref: "audit:pro-human-authoring-root",
    pro_path: "/Users/anipotts/Projects/claudeface",
    canonical_host_role: "source",
  }),
  personalCleanupProject({
    project_id: "project-pro-projects-claudemon",
    project_key: "pro-projects-claudemon",
    display_name: "claudemon",
    entity_ref: "audit:pro-human-authoring-root",
    pro_path: "/Users/anipotts/Projects/claudemon",
    canonical_host_role: "source",
  }),
  personalCleanupProject({
    project_id: "project-pro-projects-four-twenty",
    project_key: "pro-projects-four-twenty",
    display_name: "four-twenty",
    entity_ref: "audit:pro-human-authoring-root",
    pro_path: "/Users/anipotts/Projects/four-twenty",
    canonical_host_role: "source",
  }),
  personalCleanupProject({
    project_id: "project-pro-projects-glasskeeper",
    project_key: "pro-projects-glasskeeper",
    display_name: "glasskeeper",
    entity_ref: "audit:pro-human-authoring-root",
    pro_path: "/Users/anipotts/Projects/glasskeeper",
    canonical_host_role: "source",
  }),
  personalCleanupProject({
    project_id: "project-pro-projects-labs",
    project_key: "pro-projects-labs",
    display_name: "labs",
    entity_ref: "audit:pro-human-authoring-root",
    pro_path: "/Users/anipotts/Projects/labs",
    canonical_host_role: "source",
  }),
  personalCleanupProject({
    project_id: "project-pro-projects-opencursor",
    project_key: "pro-projects-opencursor",
    display_name: "opencursor",
    entity_ref: "audit:pro-human-authoring-root",
    pro_path: "/Users/anipotts/Projects/opencursor",
    canonical_host_role: "source",
  }),
  personalCleanupProject({
    project_id: "project-pro-projects-pr-cart",
    project_key: "pro-projects-pr-cart",
    display_name: "pr-cart",
    entity_ref: "audit:pro-human-authoring-root",
    pro_path: "/Users/anipotts/Projects/pr-cart",
    canonical_host_role: "source",
  }),
  personalCleanupProject({
    project_id: "project-pro-projects-quantercise",
    project_key: "pro-projects-quantercise",
    display_name: "quantercise",
    entity_ref: "audit:pro-human-authoring-root",
    pro_path: "/Users/anipotts/Projects/quantercise",
    canonical_host_role: "source",
  }),
  personalCleanupProject({
    project_id: "project-pro-projects-rudy",
    project_key: "pro-projects-rudy",
    display_name: "rudy",
    entity_ref: "audit:rudy-aligned-89ad643",
    repository: "anipotts/rudy",
    canonical_remote: "https://github.com/anipotts/rudy.git",
    pro_path: "/Users/anipotts/Projects/rudy",
    canonical_host_role: "source",
  }),
  personalCleanupProject({
    project_id: "project-mini-projects-rudy",
    project_key: "mini-projects-rudy",
    display_name: "rudy mini runtime",
    entity_ref: "audit:rudy-aligned-89ad643",
    repository: "anipotts/rudy",
    canonical_remote: "https://github.com/anipotts/rudy.git",
    mini_path: "/Users/anipotts/Projects/rudy",
    canonical_host_role: "runtime",
  }),
  personalCleanupProject({
    project_id: "project-mini-projects-phone-agent",
    project_key: "mini-projects-phone-agent",
    display_name: "phone-agent",
    entity_ref: "audit:phone-agent-no-git-role-codex-project",
    mini_path: "/Users/anipotts/Projects/phone-agent",
    canonical_host_role: "scratch",
    lifecycle: "review",
  }),
  personalCleanupProject({
    project_id: "project-mini-code-brain",
    project_key: "mini-code-brain",
    display_name: "brain mini legacy",
    entity_ref: "audit:brain-parity-mismatch",
    mini_path: "/Users/anipotts/Code/projects/brain",
    canonical_host_role: "mirror",
  }),
  personalCleanupProject({
    project_id: "project-mini-code-anipotts-com",
    project_key: "mini-code-anipotts-com",
    display_name: "anipotts-com mini legacy",
    entity_ref: "audit:mini-legacy-code-project",
    owner_chief: "chief/site",
    repository: "anipotts/anipotts.com",
    canonical_remote: "https://github.com/anipotts/anipotts.com.git",
    mini_path: "/Users/anipotts/Code/projects/anipotts-com",
    canonical_host_role: "mirror",
  }),
  personalCleanupProject({
    project_id: "project-mini-code-health",
    project_key: "mini-code-health",
    display_name: "health mini runtime",
    domain: "health",
    entity_ref: "audit:health-non-git-runtime",
    owner_chief: "chief/health",
    mini_path: "/Users/anipotts/Code/projects/health",
    canonical_host_role: "runtime",
  }),
  personalCleanupProject({
    project_id: "project-mini-code-kalshi-amma",
    project_key: "mini-code-kalshi-amma",
    display_name: "kalshi-amma mini legacy",
    domain: "finance",
    entity_ref: "audit:kalshi-durability-undecided",
    mini_path: "/Users/anipotts/Code/projects/kalshi-amma",
    canonical_host_role: "scratch",
    lifecycle: "review",
  }),
  personalCleanupProject({
    project_id: "project-mini-code-x-reader",
    project_key: "mini-code-x-reader",
    display_name: "x-reader mini legacy",
    entity_ref: "audit:x-reader-pro-source-unborn-mini",
    mini_path: "/Users/anipotts/Code/projects/x-reader",
    canonical_host_role: "mirror",
    lifecycle: "review",
  }),
];

export const fixtureProjectStates: AdminProjectState[] = [
  {
    project_id: "project-admin-control-plane",
    dedupe_key: "project:admin-control-plane",
    project_key: "admin-control-plane",
    display_name: "admin control plane",
    domain: "fleet",
    entity_ref: "repo:anipotts-com:admin",
    owner_chief: "chief/site",
    repository: "anipotts/anipotts.com",
    canonical_remote: "https://github.com/anipotts/anipotts.com.git",
    pro_path: "/Users/anipotts/Code/projects/anipotts-com",
    mini_path: "/Users/anipotts/Code/projects/anipotts-com",
    canonical_host_role: "source",
    lifecycle: "active",
    attention_kind: "review",
    last_observed_at: NOW,
    agent_source: "codex",
    event_refs: ["evt-admin-contract-2026-07-02"],
    task_refs: [
      "task-admin-work-core-contract",
      "task-admin-mcp-projection-parity",
    ],
  },
  {
    project_id: "project-agent-runtime-connect",
    dedupe_key: "project:agent-runtime-connect",
    project_key: "agent-runtime-connect",
    display_name: "agent runtime connect",
    domain: "infra",
    entity_ref: "onepassword-connect:agent-runtime",
    owner_chief: "chief/infra",
    repository: "anipotts/Infra",
    canonical_remote: "https://github.com/anipotts/Infra.git",
    pro_path: "/Users/anipotts/Infra",
    mini_path: "/Users/anipotts/Infra",
    canonical_host_role: "runtime",
    lifecycle: "planned",
    attention_kind: "approval",
    last_observed_at: NOW,
    agent_source: "codex",
    event_refs: ["evt-connect-topology-diff-2026-07-02"],
    task_refs: ["task-connect-topology-approval"],
  },
  {
    project_id: "project-rayban-closeout",
    dedupe_key: "project:brand:rayban-closeout",
    project_key: "brand-rayban-closeout",
    display_name: "ray-ban closeout",
    domain: "brand",
    entity_ref: "brand-deal:rayban-meta",
    owner_chief: "chief/brand",
    repository: "anipotts/Brand",
    canonical_remote: "https://github.com/anipotts/Brand.git",
    pro_path: "/Users/anipotts/Brand",
    mini_path: "/Users/anipotts/Brand",
    canonical_host_role: "source",
    lifecycle: "active",
    attention_kind: "verification",
    last_observed_at: "2026-07-09T00:00:00.000Z",
    agent_source: "mixed",
    event_refs: ["evt-gmail-sent-rayban-30-day-analytics-2026-07-08"],
    task_refs: ["task-rayban-payment-proof"],
  },
  {
    project_id: "project-jobs-operating-system",
    dedupe_key: "project:jobs-operating-system",
    project_key: "jobs-operating-system",
    display_name: "jobs operating system",
    domain: "work",
    entity_ref: "repo:personal-jobs",
    owner_chief: "chief/jobs",
    repository: "anipotts/jobs",
    canonical_remote: "https://github.com/anipotts/jobs.git",
    pro_path: "/Users/anipotts/Personal/jobs",
    mini_path: "/Users/anipotts/Personal/jobs",
    canonical_host_role: "source",
    lifecycle: "active",
    attention_kind: "review",
    last_observed_at: "2026-07-15T15:00:00.000Z",
    agent_source: "codex",
    event_refs: ["evt-site-jobs-migration-2026-07-15"],
    task_refs: [
      "task-site-jobs-source",
      "task-site-jobs-controller",
      "task-site-jobs-destination",
    ],
  },
  {
    project_id: "project-personal-system-cleanup",
    dedupe_key: "project:personal-system-cleanup",
    project_key: "personal-system-cleanup",
    display_name: "personal system cleanup",
    domain: "work",
    entity_ref: "audit:personal-system-cleanup:2026-07-15",
    owner_chief: "fleet/boss",
    repository: "anipotts/Infra",
    canonical_remote: "https://github.com/anipotts/Infra.git",
    pro_path: null,
    mini_path: null,
    canonical_host_role: "source",
    lifecycle: "active",
    attention_kind: "review",
    last_observed_at: PERSONAL_SYSTEM_CLEANUP_AT,
    agent_source: "codex",
    event_refs: [PERSONAL_SYSTEM_CLEANUP_EVENT_ID],
    task_refs: [PERSONAL_SYSTEM_CLEANUP_TASK_ID],
  },
  ...personalSystemCleanupProjectStates,
];

export const fixtureTaskStates: AdminTaskState[] = [
  {
    task_id: "task-admin-work-core-contract",
    dedupe_key: "task:admin-work-core-contract",
    native_thread_id: "019ed10b-518a-7d80-814b-cb52f7453646",
    machine: "ap-mini",
    host: "ap-mini.local",
    project_ref: "project-admin-control-plane",
    cwd: "/Users/anipotts/.codex/worktrees/mini-admin-work-core-2026-07-15/anipotts-com",
    goal: "implement mini-owned admin work core projections",
    current_summary:
      "project, task, lineage, inbox metadata, api, and mcp contracts are fixture-backed.",
    final_summary: null,
    next_action:
      "chief/site reviews and integrates the read-only contract locally",
    proof_refs: ["commit:935a508"],
    lifecycle: "active",
    attention_kind: "review",
    native_runtime_status: "active",
    created_at: "2026-07-15T15:00:00.000Z",
    updated_at: NOW,
    completed_at: null,
    agent_source: "codex",
    event_refs: ["evt-admin-contract-2026-07-02"],
    blocked_by: [],
  },
  {
    task_id: "task-admin-mcp-projection-parity",
    dedupe_key: "task:admin-mcp-projection-parity",
    native_thread_id: null,
    machine: "ap-mini",
    host: "ap-mini.local",
    project_ref: "project-admin-control-plane",
    cwd: "/Users/anipotts/.codex/worktrees/mini-admin-work-core-2026-07-15/anipotts-com",
    goal: "keep api and mcp project/task/lineage reads in parity",
    current_summary:
      "mcp resources and tools expose the same projection arrays as the api.",
    final_summary: null,
    next_action: "exercise detail reads before local ui integration",
    proof_refs: ["test:admin-control", "test:admin-routes"],
    lifecycle: "active",
    attention_kind: "verification",
    native_runtime_status: "idle",
    created_at: "2026-07-15T15:00:00.000Z",
    updated_at: NOW,
    completed_at: null,
    agent_source: "codex",
    event_refs: ["evt-admin-contract-2026-07-02"],
    blocked_by: ["task-admin-work-core-contract"],
  },
  {
    task_id: "task-connect-topology-approval",
    dedupe_key: "task:connect-topology-approval",
    native_thread_id: null,
    machine: "ap-mini",
    host: "ap-mini.local",
    project_ref: "project-agent-runtime-connect",
    cwd: "/Users/anipotts/Infra",
    goal: "wait for exact approval before runtime connect daemon or auth changes",
    current_summary:
      "runtime setup remains explicit approval only; no auth, env, or daemon change is implied by this projection.",
    final_summary: null,
    next_action: "hold until a signed connect runtime operation exists",
    proof_refs: ["event:evt-connect-topology-diff-2026-07-02"],
    lifecycle: "planned",
    attention_kind: "approval",
    native_runtime_status: "notLoaded",
    created_at: NOW,
    updated_at: NOW,
    completed_at: null,
    agent_source: "codex",
    event_refs: ["evt-connect-topology-diff-2026-07-02"],
    blocked_by: [],
  },
  {
    task_id: "task-rayban-payment-proof",
    dedupe_key: "task:brand:rayban-payment-proof",
    native_thread_id: null,
    machine: "ap-pro",
    host: "ap-pro.local",
    project_ref: "project-rayban-closeout",
    cwd: "/Users/anipotts/Brand",
    goal: "track payment proof after completed ray-ban 30-day sent-mail proof",
    current_summary:
      "payment proof remains a follow-up item; sent mail metadata is event proof only.",
    final_summary: null,
    next_action: "verify payment proof when brand receives it",
    proof_refs: ["event:evt-gmail-sent-rayban-30-day-analytics-2026-07-08"],
    lifecycle: "blocked",
    attention_kind: "verification",
    native_runtime_status: "idle",
    created_at: "2026-07-09T00:00:00.000Z",
    updated_at: "2026-07-09T00:00:00.000Z",
    completed_at: null,
    agent_source: "mixed",
    event_refs: ["evt-gmail-sent-rayban-30-day-analytics-2026-07-08"],
    blocked_by: [],
  },
  {
    task_id: "task-site-jobs-source",
    dedupe_key: "task:migration:site-jobs:source",
    native_thread_id: "019f1438-ed64-7362-9582-d87a17bbc08a",
    machine: "ap-pro",
    host: "ap-pro.local",
    project_ref: "project-jobs-operating-system",
    cwd: "/Users/anipotts/Personal/jobs",
    goal: "preserve the source jobs task context before migration",
    current_summary:
      "source task is parked as metadata-only context for destination reconciliation.",
    final_summary: "source task preserved without raw execution payloads",
    next_action: "use destination task as the current owner",
    proof_refs: ["migration:site-jobs:source"],
    lifecycle: "complete",
    attention_kind: "verification",
    native_runtime_status: "idle",
    created_at: "2026-07-14T18:00:00.000Z",
    updated_at: "2026-07-15T15:00:00.000Z",
    completed_at: "2026-07-15T15:00:00.000Z",
    agent_source: "codex",
    event_refs: ["evt-site-jobs-migration-2026-07-15"],
    blocked_by: [],
  },
  {
    task_id: "task-site-jobs-controller",
    dedupe_key: "task:migration:site-jobs:controller",
    native_thread_id: "019f5da8-4a3c-7722-a1bf-0fca16e83e85",
    machine: "ap-mini",
    host: "ap-mini.local",
    project_ref: "project-jobs-operating-system",
    cwd: "/Users/anipotts/.codex/worktrees/site-jobs-controller/anipotts-com",
    goal: "controller worktree verifies source and destination task continuity",
    current_summary:
      "controller links source task and destination task into one lineage group.",
    final_summary: "controller reconciliation finished",
    next_action: "handoff to destination task",
    proof_refs: ["migration:site-jobs:controller"],
    lifecycle: "complete",
    attention_kind: "verification",
    native_runtime_status: "idle",
    created_at: "2026-07-15T14:00:00.000Z",
    updated_at: "2026-07-15T15:00:00.000Z",
    completed_at: "2026-07-15T15:00:00.000Z",
    agent_source: "codex",
    event_refs: ["evt-site-jobs-migration-2026-07-15"],
    blocked_by: ["task-site-jobs-source"],
  },
  {
    task_id: "task-site-jobs-destination",
    dedupe_key: "task:migration:site-jobs:destination",
    native_thread_id: "019f5da8-destination-synthetic",
    machine: "ap-mini",
    host: "ap-mini.local",
    project_ref: "project-jobs-operating-system",
    cwd: "/Users/anipotts/Personal/jobs",
    goal: "continue jobs work from migrated context",
    current_summary:
      "destination task owns the current jobs lane after source and controller reconciliation.",
    final_summary: null,
    next_action: "continue only from destination task state",
    proof_refs: ["migration:site-jobs:destination"],
    lifecycle: "active",
    attention_kind: "review",
    native_runtime_status: "idle",
    created_at: "2026-07-15T15:00:00.000Z",
    updated_at: "2026-07-15T15:00:00.000Z",
    completed_at: null,
    agent_source: "codex",
    event_refs: ["evt-site-jobs-migration-2026-07-15"],
    blocked_by: ["task-site-jobs-controller"],
  },
  {
    task_id: PERSONAL_SYSTEM_CLEANUP_TASK_ID,
    dedupe_key: "task:personal-system-cleanup:current",
    native_thread_id: null,
    machine: "ap-mini",
    host: "ap-mini.local",
    project_ref: "project-personal-system-cleanup",
    cwd: "/Users/anipotts/Infra",
    goal: "sequence personal system cleanup after durable-root audit",
    current_summary:
      "ordered cleanup workstream is modeled as one Work task; root-level reconciliation stays metadata-only until exact proof and approval.",
    final_summary: null,
    next_action:
      "route root reconciliation to owner chiefs, keep GitHub main as committed truth, use pro for human authoring, and keep mini runtime mirrors clean.",
    proof_refs: ["audit:personal-system-cleanup:2026-07-15"],
    lifecycle: "active",
    attention_kind: "review",
    native_runtime_status: "idle",
    created_at: PERSONAL_SYSTEM_CLEANUP_AT,
    updated_at: PERSONAL_SYSTEM_CLEANUP_AT,
    completed_at: null,
    agent_source: "codex",
    event_refs: [PERSONAL_SYSTEM_CLEANUP_EVENT_ID],
    blocked_by: [],
  },
];

export const fixtureTaskLineage: AdminTaskLineage[] = [
  {
    lineage_id: "lineage-admin-core-root",
    lineage_group_id: "lineage-group-admin-core",
    task_ref: "task-admin-work-core-contract",
    parent_task_ref: null,
    root_task_ref: "task-admin-work-core-contract",
    relation: "root",
    controller_ref: null,
    agent_source: "codex",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
  {
    lineage_id: "lineage-admin-mcp-after-contract",
    lineage_group_id: "lineage-group-admin-core",
    task_ref: "task-admin-mcp-projection-parity",
    parent_task_ref: "task-admin-work-core-contract",
    root_task_ref: "task-admin-work-core-contract",
    relation: "derived_from",
    controller_ref: null,
    agent_source: "codex",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
  {
    lineage_id: "lineage-rayban-payment-from-sent-proof",
    lineage_group_id: "lineage-group-rayban-closeout",
    task_ref: "task-rayban-payment-proof",
    parent_task_ref: null,
    root_task_ref: "task-rayban-payment-proof",
    relation: "follow_up_from_event",
    controller_ref: null,
    agent_source: "mixed",
    event_refs: ["evt-gmail-sent-rayban-30-day-analytics-2026-07-08"],
    updated_at: "2026-07-09T00:00:00.000Z",
  },
  {
    lineage_id: "lineage-site-jobs-source",
    lineage_group_id: "lineage-group-site-jobs-migration",
    task_ref: "task-site-jobs-source",
    parent_task_ref: null,
    root_task_ref: "task-site-jobs-source",
    relation: "source",
    controller_ref: "task-site-jobs-controller",
    agent_source: "codex",
    event_refs: ["evt-site-jobs-migration-2026-07-15"],
    updated_at: "2026-07-15T15:00:00.000Z",
  },
  {
    lineage_id: "lineage-site-jobs-controller",
    lineage_group_id: "lineage-group-site-jobs-migration",
    task_ref: "task-site-jobs-controller",
    parent_task_ref: "task-site-jobs-source",
    root_task_ref: "task-site-jobs-source",
    relation: "controller_worktree",
    controller_ref: "task-site-jobs-controller",
    agent_source: "codex",
    event_refs: ["evt-site-jobs-migration-2026-07-15"],
    updated_at: "2026-07-15T15:00:00.000Z",
  },
  {
    lineage_id: "lineage-site-jobs-destination",
    lineage_group_id: "lineage-group-site-jobs-migration",
    task_ref: "task-site-jobs-destination",
    parent_task_ref: "task-site-jobs-controller",
    root_task_ref: "task-site-jobs-source",
    relation: "destination",
    controller_ref: "task-site-jobs-controller",
    agent_source: "codex",
    event_refs: ["evt-site-jobs-migration-2026-07-15"],
    updated_at: "2026-07-15T15:00:00.000Z",
  },
];

export const fixturePieceStates: AdminPieceState[] = [
  {
    piece_id: "piece-newsletter-agent-control-plane",
    dedupe_key: "piece:newsletter:agent-control-plane",
    event_refs: ["evt-admin-contract-2026-07-02"],
    title: "first newsletter on agent control planes",
    state: "draft",
    channels: ["newsletter", "writing", "x-thread"],
    source_refs: ["apps/www/src/content/writing"],
    updated_at: NOW,
  },
  {
    piece_id: "piece-carousel-durable-agent-workflows",
    dedupe_key: "piece:carousel:durable-agent-workflows-v2",
    event_refs: ["evt-admin-contract-2026-07-02"],
    title: "durable agent workflows carousel",
    state: "review",
    channels: ["carousel", "instagram", "tiktok"],
    source_refs: ["apps/admin/src/data/static/carousels"],
    updated_at: NOW,
  },
];

export const fixtureFleetStatus: AdminFleetStatus[] = [
  {
    subject_id: "machine-ap-pro",
    kind: "machine",
    title: "ap-pro",
    status: "human editing",
    summary: "local preview and creation host for admin/site UI work.",
    owner: "ani",
    href: "/fleet",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
  {
    subject_id: "machine-ap-mini",
    kind: "machine",
    title: "ap-mini",
    status: "runtime canonical",
    summary: "event core, projections, services, and clean mirrors live here.",
    owner: "codex chief",
    href: "/fleet",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
  {
    subject_id: "fleet-personal-structural-migration-coverage",
    kind: "cleanup-coverage",
    title: "personal structural migration coverage",
    status: "verified audit",
    summary:
      "GitHub main is committed truth; ap-pro is source and human authoring; ap-mini is runtime, mirrors, and services.",
    owner: "fleet/boss",
    href: "/fleet",
    event_refs: [PERSONAL_SYSTEM_CLEANUP_EVENT_ID],
    updated_at: PERSONAL_SYSTEM_CLEANUP_AT,
  },
  {
    subject_id: "fleet-personal-routing-coverage",
    kind: "cleanup-routing",
    title: "personal cleanup routing coverage",
    status: "active",
    summary:
      "cleanup is routed by durable root and owner chief; umbrella Code and Projects roots remain observed context only.",
    owner: "fleet/boss",
    href: "/fleet",
    event_refs: [PERSONAL_SYSTEM_CLEANUP_EVENT_ID],
    updated_at: PERSONAL_SYSTEM_CLEANUP_AT,
  },
  {
    subject_id: "fleet-compatibility-alias-drain",
    kind: "compatibility-alias",
    title: "compatibility alias drain",
    status: "gated",
    summary:
      "compatibility aliases and legacy paths drain only after live consumer proof; no symlink or path removal is implied.",
    owner: "chief/infra",
    href: "/fleet",
    event_refs: [PERSONAL_SYSTEM_CLEANUP_EVENT_ID],
    updated_at: PERSONAL_SYSTEM_CLEANUP_AT,
  },
  {
    subject_id: "fleet-personal-documented-exceptions",
    kind: "documented-exception",
    title: "personal cleanup documented exceptions",
    status: "tracked",
    summary:
      "rudy aligned at 89ad643; brain has parity mismatch; x-reader has pro source versus unborn mini; health is intentional non-Git runtime; phone-agent lacks Git, role, and Codex project; kalshi durability is undecided.",
    owner: "fleet/boss",
    href: "/fleet",
    event_refs: [PERSONAL_SYSTEM_CLEANUP_EVENT_ID],
    updated_at: PERSONAL_SYSTEM_CLEANUP_AT,
  },
];

export const fixtureDeployStates: AdminDeployState[] = [
  {
    deploy_id: "deploy-admin-only-green-check",
    target: "admin.anipotts.com",
    status: "approved after checks",
    scope: "admin-only diff classifier, typecheck, build, preview proof",
    href: "/deploys",
    last_run_at: null,
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
];

export const fixtureCapabilityStates: AdminCapabilityState[] = [
  {
    capability_id: "mcp-readonly-ap-pro",
    machine: "ap-pro",
    status: "planned",
    auth_model: "cloudflare-access-service-token-per-machine",
    write_enabled: false,
    summary: "read-only projections for local pro site agents.",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
  {
    capability_id: "mcp-readonly-ap-mini",
    machine: "ap-mini",
    status: "planned",
    auth_model: "cloudflare-access-service-token-per-machine",
    write_enabled: false,
    summary: "read-only projections for runtime and fleet agents.",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
  {
    capability_id: "gmail-metadata-nyu",
    machine: "ap-pro",
    status: "temporary",
    auth_model: "metadata-only",
    write_enabled: false,
    summary: "ap7564@nyu.edu metadata adapter expires 2026-08-31.",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
];

export const fixtureServiceRegistryView: AdminServiceRegistryViewItem[] = [
  {
    service_id: "svc-admin-api",
    name: "admin api",
    hostname: "admin.anipotts.com",
    visibility: "protected",
    owner: "codex chief",
    status: "contract first",
    updated_at: NOW,
    event_refs: ["evt-admin-contract-2026-07-02"],
  },
];

export const fixtureProjections: AdminControlProjections = {
  inbox_items: fixtureInboxItems,
  project_states: fixtureProjectStates,
  task_states: fixtureTaskStates,
  task_lineage: fixtureTaskLineage,
  piece_states: fixturePieceStates,
  fleet_status: fixtureFleetStatus,
  deploy_states: fixtureDeployStates,
  capability_states: fixtureCapabilityStates,
  service_registry_view: fixtureServiceRegistryView,
};
