import {
  ADMIN_EVENT_SCHEMA_VERSION,
  type AdminCapabilityState,
  type AdminControlContracts,
  type AdminControlProjections,
  type AdminDeployState,
  type AdminEventEnvelope,
  type AdminFleetStatus,
  type AdminInboxItem,
  type AdminPieceState,
  type AdminProjectState,
  type AdminServiceRegistryViewItem,
  type AdminTaskLineage,
  type AdminTaskState,
} from "./types";
import {
  buildSentMailAwareness,
  buildSentMailMetadata,
  gmailSentDedupeKey,
} from "./sent-mail";

const NOW = "2026-07-02T16:45:00.000Z";
const RAYBAN_SENT_AT = "2026-07-08T00:00:00.000Z";

const raybanSentMail = buildSentMailMetadata({
  account: "hello@anipotts.com",
  sent_ref: "rayban-30-day-analytics-2026-07-08",
  subject: "Ray-Ban 30-day analytics",
  sent_at: RAYBAN_SENT_AT,
  has_attachments: "unknown",
  href: "metadata://gmail/sent/rayban-30-day-analytics-2026-07-08",
});

const raybanSentAwareness = buildSentMailAwareness(raybanSentMail, {
  completed: true,
  dedupe_key: gmailSentDedupeKey("rayban-30-day-analytics-2026-07-08"),
  event_id: "evt-gmail-sent-rayban-30-day-analytics-2026-07-08",
  privacy: "private",
});

const raybanPaymentFollowUp = buildSentMailAwareness(raybanSentMail, {
  completed: true,
  dedupe_key: gmailSentDedupeKey("rayban-30-day-analytics-2026-07-08"),
  event_id: "evt-gmail-sent-rayban-30-day-analytics-2026-07-08",
  privacy: "private",
  follow_up: {
    id: "inbox-rayban-payment-followup",
    dedupe_key: "brand:rayban-meta:payment-followup:2026-07-09",
    kind: "payment",
    title: "ray-ban payment follow-up",
    summary:
      "30-day sent mail and acknowledgement are proof; payment follow-up stays separate.",
    owner: "chief/brand",
    domain: "brand",
    entity_ref: "brand-deal:rayban-meta",
    attention_kind: "waiting",
    urgency: "normal",
    status: "waiting_payment_proof",
    href: raybanSentMail.href,
    last_seen_at: "2026-07-09T00:00:00.000Z",
  },
});

export const adminControlContracts: AdminControlContracts = {
  event_fields: [
    "schema_version",
    "event_id",
    "dedupe_key",
    "source",
    "provider",
    "account",
    "actor",
    "kind",
    "ts",
    "privacy",
    "title",
    "summary",
    "href",
    "payload_ref",
    "created_by",
  ],
  inbox_card_fields: [
    "item_id",
    "dedupe_key",
    "event_refs",
    "domain",
    "entity_ref",
    "attention_kind",
    "source",
    "account",
    "title",
    "summary",
    "href",
    "status",
    "urgency",
    "owner",
    "action_kind",
    "expires_at",
    "last_seen_at",
  ],
  project_state_fields: [
    "project_id",
    "dedupe_key",
    "title",
    "domain",
    "entity_ref",
    "lifecycle",
    "attention_kind",
    "native_runtime_status",
    "status_summary",
    "owner",
    "agent_source",
    "event_refs",
    "task_refs",
    "updated_at",
  ],
  task_state_fields: [
    "task_id",
    "dedupe_key",
    "project_ref",
    "title",
    "domain",
    "entity_ref",
    "lifecycle",
    "attention_kind",
    "native_runtime_status",
    "status_summary",
    "owner",
    "agent_source",
    "event_refs",
    "blocked_by",
    "updated_at",
  ],
  task_lineage_fields: [
    "lineage_id",
    "task_ref",
    "parent_task_ref",
    "root_task_ref",
    "relation",
    "agent_source",
    "event_refs",
    "updated_at",
  ],
  sent_mail_metadata_fields: [
    "account",
    "sent_ref",
    "subject",
    "sent_at",
    "has_attachments",
    "href",
  ],
  sent_mail_card_policy: {
    dedupe: "gmail-message-id-derived-ref",
    completed_obligation: "event-only",
    followups: "separate-inbox-items",
    sync: "refresh-on-open-plus-light-polling",
    raw_identifiers: "omitted",
    preview_text: "omitted",
  },
  piece_states: [
    "idea",
    "draft",
    "review",
    "export-ready",
    "publish-ready",
    "published",
    "archived",
  ],
  legal_piece_cycles: ["review -> draft", "published -> draft"],
};

export const fixtureEvents: AdminEventEnvelope[] = [
  {
    schema_version: ADMIN_EVENT_SCHEMA_VERSION,
    event_id: "evt-admin-contract-2026-07-02",
    dedupe_key: "admin:review:event-api-mcp-contract:2026-07-02",
    source: "fleet",
    provider: "admin",
    account: "admin.anipotts.com",
    actor: "codex",
    kind: "review.required",
    ts: NOW,
    privacy: "internal",
    title: "review event contract and read-only mcp",
    summary:
      "first review must cover event fields, projection api, mcp shape, retention, and inbox bento.",
    href: "/api/admin/projections",
    payload_ref: "r2://admin-event-payloads/2026/07/02/admin-contract.json",
    created_by: "codex",
  },
  raybanSentAwareness.event,
  {
    schema_version: ADMIN_EVENT_SCHEMA_VERSION,
    event_id: "evt-rayban-analytics-2026-07-02",
    dedupe_key: "brand:rayban-meta:analytics-reminder:2026-07-02",
    source: "brand",
    provider: "manual",
    account: "ray-ban meta",
    actor: "ani",
    kind: "deadline",
    ts: NOW,
    privacy: "private",
    title: "ray-ban analytics reminder",
    summary:
      "submit the 30-day analytics reminder so the deal closeout can move toward payment.",
    href: null,
    payload_ref: "r2://admin-event-payloads/2026/07/02/rayban-analytics.json",
    created_by: "codex",
  },
  {
    schema_version: ADMIN_EVENT_SCHEMA_VERSION,
    event_id: "evt-connect-topology-diff-2026-07-02",
    dedupe_key: "infra:connect:topology-diff:2026-07-02",
    source: "fleet",
    provider: "1password-connect",
    account: "agent-runtime",
    actor: "codex",
    kind: "approval.required",
    ts: NOW,
    privacy: "sensitive",
    title: "sign connect topology diff",
    summary:
      "value-serving and mcp write tools stay off until Ani signs the exact rule diff.",
    href: "/fleet",
    payload_ref:
      "r2://admin-event-payloads/2026/07/02/connect-topology-diff.json",
    created_by: "codex",
  },
  {
    schema_version: ADMIN_EVENT_SCHEMA_VERSION,
    event_id: "evt-notes-user-session-2026-07-02",
    dedupe_key: "notes:user-session-reader:todo-date:2026-07-02",
    source: "notes",
    provider: "apple-notes",
    account: "ap-pro",
    actor: "claude",
    kind: "adapter.scope",
    ts: NOW,
    privacy: "private",
    title: "daily notes reader stays user-session only",
    summary:
      "todo note import can read in a user session, never from launchd or background op.",
    href: null,
    payload_ref: "r2://admin-event-payloads/2026/07/02/notes-user-session.json",
    created_by: "codex",
  },
];

export const fixtureInboxItems: AdminInboxItem[] = [
  {
    item_id: "inbox-admin-contract-review",
    dedupe_key: "admin:review:event-api-mcp-contract:2026-07-02",
    event_refs: ["evt-admin-contract-2026-07-02"],
    domain: "admin",
    entity_ref: "admin-control:event-api-mcp-contract",
    attention_kind: "review",
    source: "fleet",
    account: "admin.anipotts.com",
    title: "review api plus mcp contract",
    summary:
      "event schema, projection api, read-only mcp, retention, and inbox bento move together.",
    href: "/api/admin/projections",
    status: "review",
    urgency: "urgent",
    owner: "codex chief",
    action_kind: "review",
    expires_at: null,
    last_seen_at: null,
  },
  raybanPaymentFollowUp.inbox_item!,
  {
    item_id: "inbox-connect-topology",
    dedupe_key: "infra:connect:topology-diff:2026-07-02",
    event_refs: ["evt-connect-topology-diff-2026-07-02"],
    domain: "infra",
    entity_ref: "onepassword-connect:agent-runtime",
    attention_kind: "approval",
    source: "fleet",
    account: "agent-runtime",
    title: "connect diff before value access",
    summary:
      "personal/business value-serving stays off; only the signed diff can open that lane.",
    href: "/fleet",
    status: "action required",
    urgency: "high",
    owner: "codex chief",
    action_kind: "approve",
    expires_at: null,
    last_seen_at: null,
  },
  {
    item_id: "inbox-notes-session-reader",
    dedupe_key: "notes:user-session-reader:todo-date:2026-07-02",
    event_refs: ["evt-notes-user-session-2026-07-02"],
    domain: "life",
    entity_ref: "notes:daily-todo-reader",
    attention_kind: "proof",
    source: "notes",
    account: "ap-pro",
    title: "notes import is user-session only",
    summary:
      "daily todo notes can enter inbox through the session reader, never a launchd reader.",
    href: null,
    status: "scoped",
    urgency: "normal",
    owner: "claude",
    action_kind: "verify",
    expires_at: null,
    last_seen_at: null,
  },
];

export const fixtureProjectStates: AdminProjectState[] = [
  {
    project_id: "project-admin-control-plane",
    dedupe_key: "project:admin-control-plane",
    title: "admin control plane",
    domain: "fleet",
    entity_ref: "repo:anipotts-com:admin",
    lifecycle: "active",
    attention_kind: "review",
    native_runtime_status: "deployed",
    status_summary:
      "read-only control-plane projections exist; write path and adapters stay gated.",
    owner: "chief/site",
    agent_source: "codex",
    event_refs: ["evt-admin-contract-2026-07-02"],
    task_refs: [
      "task-admin-work-core-contract",
      "task-admin-mcp-projection-parity",
    ],
    updated_at: NOW,
  },
  {
    project_id: "project-agent-runtime-connect",
    dedupe_key: "project:agent-runtime-connect",
    title: "agent runtime connect",
    domain: "infra",
    entity_ref: "onepassword-connect:agent-runtime",
    lifecycle: "planned",
    attention_kind: "approval",
    native_runtime_status: "none",
    status_summary:
      "vault and token design are approved; daemon, auth, and env work remain gated.",
    owner: "chief/infra",
    agent_source: "codex",
    event_refs: ["evt-connect-topology-diff-2026-07-02"],
    task_refs: ["task-connect-topology-approval"],
    updated_at: NOW,
  },
  {
    project_id: "project-rayban-closeout",
    dedupe_key: "project:brand:rayban-closeout",
    title: "ray-ban closeout",
    domain: "brand",
    entity_ref: "brand-deal:rayban-meta",
    lifecycle: "active",
    attention_kind: "waiting",
    native_runtime_status: "none",
    status_summary:
      "sent proof exists; payment follow-up is tracked separately from the completed 30-day obligation.",
    owner: "chief/brand",
    agent_source: "mixed",
    event_refs: ["evt-gmail-sent-rayban-30-day-analytics-2026-07-08"],
    task_refs: ["task-rayban-payment-proof"],
    updated_at: "2026-07-09T00:00:00.000Z",
  },
];

export const fixtureTaskStates: AdminTaskState[] = [
  {
    task_id: "task-admin-work-core-contract",
    dedupe_key: "task:admin-work-core-contract",
    project_ref: "project-admin-control-plane",
    title: "admin work core contract",
    domain: "fleet",
    entity_ref: "projection:admin-work-core",
    lifecycle: "active",
    attention_kind: "review",
    native_runtime_status: "deployed",
    status_summary:
      "domain, entity refs, attention, project state, task state, and lineage are fixture-backed.",
    owner: "chief/infra",
    agent_source: "codex",
    event_refs: ["evt-admin-contract-2026-07-02"],
    blocked_by: [],
    updated_at: NOW,
  },
  {
    task_id: "task-admin-mcp-projection-parity",
    dedupe_key: "task:admin-mcp-projection-parity",
    project_ref: "project-admin-control-plane",
    title: "api and mcp projection parity",
    domain: "fleet",
    entity_ref: "mcp:admin-control",
    lifecycle: "active",
    attention_kind: "proof",
    native_runtime_status: "deployed",
    status_summary:
      "read-only api and mcp resources expose the same project, task, and lineage arrays.",
    owner: "chief/site",
    agent_source: "codex",
    event_refs: ["evt-admin-contract-2026-07-02"],
    blocked_by: ["task-admin-work-core-contract"],
    updated_at: NOW,
  },
  {
    task_id: "task-connect-topology-approval",
    dedupe_key: "task:connect-topology-approval",
    project_ref: "project-agent-runtime-connect",
    title: "connect topology approval",
    domain: "infra",
    entity_ref: "onepassword-connect:agent-runtime",
    lifecycle: "planned",
    attention_kind: "approval",
    native_runtime_status: "none",
    status_summary:
      "runtime setup remains explicit approval only; no auth, env, or daemon change is implied by this projection.",
    owner: "chief/infra",
    agent_source: "codex",
    event_refs: ["evt-connect-topology-diff-2026-07-02"],
    blocked_by: [],
    updated_at: NOW,
  },
  {
    task_id: "task-rayban-payment-proof",
    dedupe_key: "task:brand:rayban-payment-proof",
    project_ref: "project-rayban-closeout",
    title: "ray-ban payment proof",
    domain: "brand",
    entity_ref: "brand-deal:rayban-meta",
    lifecycle: "blocked",
    attention_kind: "waiting",
    native_runtime_status: "none",
    status_summary:
      "payment proof remains a follow-up item; sent mail metadata is event proof only.",
    owner: "chief/brand",
    agent_source: "mixed",
    event_refs: ["evt-gmail-sent-rayban-30-day-analytics-2026-07-08"],
    blocked_by: [],
    updated_at: "2026-07-09T00:00:00.000Z",
  },
];

export const fixtureTaskLineage: AdminTaskLineage[] = [
  {
    lineage_id: "lineage-admin-core-root",
    task_ref: "task-admin-work-core-contract",
    parent_task_ref: null,
    root_task_ref: "task-admin-work-core-contract",
    relation: "root",
    agent_source: "codex",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
  {
    lineage_id: "lineage-admin-mcp-after-contract",
    task_ref: "task-admin-mcp-projection-parity",
    parent_task_ref: "task-admin-work-core-contract",
    root_task_ref: "task-admin-work-core-contract",
    relation: "derived_from",
    agent_source: "codex",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
  {
    lineage_id: "lineage-rayban-payment-from-sent-proof",
    task_ref: "task-rayban-payment-proof",
    parent_task_ref: null,
    root_task_ref: "task-rayban-payment-proof",
    relation: "follow_up_from_event",
    agent_source: "mixed",
    event_refs: ["evt-gmail-sent-rayban-30-day-analytics-2026-07-08"],
    updated_at: "2026-07-09T00:00:00.000Z",
  },
];

export const fixturePieceStates: AdminPieceState[] = [
  {
    piece_id: "piece-newsletter-agent-control-plane",
    dedupe_key: "piece:newsletter:agent-control-plane",
    event_refs: ["evt-admin-contract-2026-07-02"],
    title: "first newsletter on agent control planes",
    state: "draft",
    channels: ["newsletter", "writing", "x-thread"],
    source_refs: ["apps/www/src/content/writing"],
    updated_at: NOW,
  },
  {
    piece_id: "piece-carousel-durable-agent-workflows",
    dedupe_key: "piece:carousel:durable-agent-workflows-v2",
    event_refs: ["evt-admin-contract-2026-07-02"],
    title: "durable agent workflows carousel",
    state: "review",
    channels: ["carousel", "instagram", "tiktok"],
    source_refs: ["apps/admin/src/data/static/carousels"],
    updated_at: NOW,
  },
];

export const fixtureFleetStatus: AdminFleetStatus[] = [
  {
    subject_id: "machine-ap-pro",
    kind: "machine",
    title: "ap-pro",
    status: "human editing",
    summary: "local preview and creation host for admin/site UI work.",
    owner: "ani",
    href: "/fleet",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
  {
    subject_id: "machine-ap-mini",
    kind: "machine",
    title: "ap-mini",
    status: "runtime canonical",
    summary: "event core, projections, services, and clean mirrors live here.",
    owner: "codex chief",
    href: "/fleet",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
];

export const fixtureDeployStates: AdminDeployState[] = [
  {
    deploy_id: "deploy-admin-only-green-check",
    target: "admin.anipotts.com",
    status: "approved after checks",
    scope: "admin-only diff classifier, typecheck, build, preview proof",
    href: "/deploys",
    last_run_at: null,
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
];

export const fixtureCapabilityStates: AdminCapabilityState[] = [
  {
    capability_id: "mcp-readonly-ap-pro",
    machine: "ap-pro",
    status: "planned",
    auth_model: "cloudflare-access-service-token-per-machine",
    write_enabled: false,
    summary: "read-only projections for local pro site agents.",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
  {
    capability_id: "mcp-readonly-ap-mini",
    machine: "ap-mini",
    status: "planned",
    auth_model: "cloudflare-access-service-token-per-machine",
    write_enabled: false,
    summary: "read-only projections for runtime and fleet agents.",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
  {
    capability_id: "gmail-metadata-nyu",
    machine: "ap-pro",
    status: "temporary",
    auth_model: "metadata-only",
    write_enabled: false,
    summary: "ap7564@nyu.edu metadata adapter expires 2026-08-31.",
    event_refs: ["evt-admin-contract-2026-07-02"],
    updated_at: NOW,
  },
];

export const fixtureServiceRegistryView: AdminServiceRegistryViewItem[] = [
  {
    service_id: "svc-admin-api",
    name: "admin api",
    hostname: "admin.anipotts.com",
    visibility: "protected",
    owner: "codex chief",
    status: "contract first",
    updated_at: NOW,
    event_refs: ["evt-admin-contract-2026-07-02"],
  },
];

export const fixtureProjections: AdminControlProjections = {
  inbox_items: fixtureInboxItems,
  project_states: fixtureProjectStates,
  task_states: fixtureTaskStates,
  task_lineage: fixtureTaskLineage,
  piece_states: fixturePieceStates,
  fleet_status: fixtureFleetStatus,
  deploy_states: fixtureDeployStates,
  capability_states: fixtureCapabilityStates,
  service_registry_view: fixtureServiceRegistryView,
};
