// Generated by scripts/brand/build-marks.mjs from packages/brand/marks.
// Do not edit: run `pnpm brand:marks` after changing a vendored mark.
import sprite from "../marks/sprite.svg?url&no-inline";
import mark1passwordPng from "../marks/img/1password-112.png?url&no-inline";
import mark1passwordWebp112 from "../marks/img/1password-112.webp?url&no-inline";
import mark1passwordWebp56 from "../marks/img/1password-56.webp?url&no-inline";
import apMiniPng from "../marks/img/ap-mini-112.png?url&no-inline";
import apMiniWebp112 from "../marks/img/ap-mini-112.webp?url&no-inline";
import apMiniWebp56 from "../marks/img/ap-mini-56.webp?url&no-inline";
import apPhonePng from "../marks/img/ap-phone-112.png?url&no-inline";
import apPhoneWebp112 from "../marks/img/ap-phone-112.webp?url&no-inline";
import apPhoneWebp56 from "../marks/img/ap-phone-56.webp?url&no-inline";
import apPlusPng from "../marks/img/ap-plus-112.png?url&no-inline";
import apPlusWebp112 from "../marks/img/ap-plus-112.webp?url&no-inline";
import apPlusWebp56 from "../marks/img/ap-plus-56.webp?url&no-inline";
import apProPng from "../marks/img/ap-pro-112.png?url&no-inline";
import apProWebp112 from "../marks/img/ap-pro-112.webp?url&no-inline";
import apProWebp56 from "../marks/img/ap-pro-56.webp?url&no-inline";
import applehealthPng from "../marks/img/applehealth-112.png?url&no-inline";
import applehealthWebp112 from "../marks/img/applehealth-112.webp?url&no-inline";
import applehealthWebp56 from "../marks/img/applehealth-56.webp?url&no-inline";
import calendarPng from "../marks/img/calendar-112.png?url&no-inline";
import calendarWebp112 from "../marks/img/calendar-112.webp?url&no-inline";
import calendarWebp56 from "../marks/img/calendar-56.webp?url&no-inline";
import chatgptPng from "../marks/img/chatgpt-112.png?url&no-inline";
import chatgptWebp112 from "../marks/img/chatgpt-112.webp?url&no-inline";
import chatgptWebp56 from "../marks/img/chatgpt-56.webp?url&no-inline";
import chatgptAtlasPng from "../marks/img/chatgpt-atlas-112.png?url&no-inline";
import chatgptAtlasWebp112 from "../marks/img/chatgpt-atlas-112.webp?url&no-inline";
import chatgptAtlasWebp56 from "../marks/img/chatgpt-atlas-56.webp?url&no-inline";
import chromePng from "../marks/img/chrome-112.png?url&no-inline";
import chromeWebp112 from "../marks/img/chrome-112.webp?url&no-inline";
import chromeWebp56 from "../marks/img/chrome-56.webp?url&no-inline";
import claudeSvg from "../marks/img/claude.svg?url&no-inline";
import codexPng from "../marks/img/codex-112.png?url&no-inline";
import codexWebp112 from "../marks/img/codex-112.webp?url&no-inline";
import codexWebp56 from "../marks/img/codex-56.webp?url&no-inline";
import contactsPng from "../marks/img/contacts-112.png?url&no-inline";
import contactsWebp112 from "../marks/img/contacts-112.webp?url&no-inline";
import contactsWebp56 from "../marks/img/contacts-56.webp?url&no-inline";
import gmailPng from "../marks/img/gmail-112.png?url&no-inline";
import gmailWebp112 from "../marks/img/gmail-112.webp?url&no-inline";
import gmailWebp56 from "../marks/img/gmail-56.webp?url&no-inline";
import googlecalendarPng from "../marks/img/googlecalendar-112.png?url&no-inline";
import googlecalendarWebp112 from "../marks/img/googlecalendar-112.webp?url&no-inline";
import googlecalendarWebp56 from "../marks/img/googlecalendar-56.webp?url&no-inline";
import googledrivePng from "../marks/img/googledrive-112.png?url&no-inline";
import googledriveWebp112 from "../marks/img/googledrive-112.webp?url&no-inline";
import googledriveWebp56 from "../marks/img/googledrive-56.webp?url&no-inline";
import granolaPng from "../marks/img/granola-112.png?url&no-inline";
import granolaWebp112 from "../marks/img/granola-112.webp?url&no-inline";
import granolaWebp56 from "../marks/img/granola-56.webp?url&no-inline";
import instagramPng from "../marks/img/instagram-112.png?url&no-inline";
import instagramWebp112 from "../marks/img/instagram-112.webp?url&no-inline";
import instagramWebp56 from "../marks/img/instagram-56.webp?url&no-inline";
import lexarPng from "../marks/img/lexar-112.png?url&no-inline";
import lexarWebp112 from "../marks/img/lexar-112.webp?url&no-inline";
import lexarWebp56 from "../marks/img/lexar-56.webp?url&no-inline";
import linkedinPng from "../marks/img/linkedin-112.png?url&no-inline";
import linkedinWebp112 from "../marks/img/linkedin-112.webp?url&no-inline";
import linkedinWebp56 from "../marks/img/linkedin-56.webp?url&no-inline";
import mercuryPng from "../marks/img/mercury-112.png?url&no-inline";
import mercuryWebp112 from "../marks/img/mercury-112.webp?url&no-inline";
import mercuryWebp56 from "../marks/img/mercury-56.webp?url&no-inline";
import messagesPng from "../marks/img/messages-112.png?url&no-inline";
import messagesWebp112 from "../marks/img/messages-112.webp?url&no-inline";
import messagesWebp56 from "../marks/img/messages-56.webp?url&no-inline";
import notesPng from "../marks/img/notes-112.png?url&no-inline";
import notesWebp112 from "../marks/img/notes-112.webp?url&no-inline";
import notesWebp56 from "../marks/img/notes-56.webp?url&no-inline";
import obsidianPng from "../marks/img/obsidian-112.png?url&no-inline";
import obsidianWebp112 from "../marks/img/obsidian-112.webp?url&no-inline";
import obsidianWebp56 from "../marks/img/obsidian-56.webp?url&no-inline";
import safariPng from "../marks/img/safari-112.png?url&no-inline";
import safariWebp112 from "../marks/img/safari-112.webp?url&no-inline";
import safariWebp56 from "../marks/img/safari-56.webp?url&no-inline";
import spotifyPng from "../marks/img/spotify-112.png?url&no-inline";
import spotifyWebp112 from "../marks/img/spotify-112.webp?url&no-inline";
import spotifyWebp56 from "../marks/img/spotify-56.webp?url&no-inline";
import stripePng from "../marks/img/stripe-112.png?url&no-inline";
import stripeWebp112 from "../marks/img/stripe-112.webp?url&no-inline";
import stripeWebp56 from "../marks/img/stripe-56.webp?url&no-inline";
import tailscalePng from "../marks/img/tailscale-112.png?url&no-inline";
import tailscaleWebp112 from "../marks/img/tailscale-112.webp?url&no-inline";
import tailscaleWebp56 from "../marks/img/tailscale-56.webp?url&no-inline";
import voicememosPng from "../marks/img/voicememos-112.png?url&no-inline";
import voicememosWebp112 from "../marks/img/voicememos-112.webp?url&no-inline";
import voicememosWebp56 from "../marks/img/voicememos-56.webp?url&no-inline";
import whatsappPng from "../marks/img/whatsapp-112.png?url&no-inline";
import whatsappWebp112 from "../marks/img/whatsapp-112.webp?url&no-inline";
import whatsappWebp56 from "../marks/img/whatsapp-56.webp?url&no-inline";

/** One cached sprite holding every flat glyph as a <symbol>. */
export const MARK_SPRITE: string = sprite;

/** The glyph ids inside the sprite. */
export const MARK_GLYPHS = [
  "buttondown",
  "cloudflare",
  "github",
  "linear",
  "npm",
  "resend",
  "vercel",
  "x",
  "youtube",
] as const;

/** Artwork fetched lazily per mark: WebP at 2x and 4x of the 28px tile with a
 * PNG fallback, or one standalone vector. */
export const MARK_FILES = {
  "1password": {
    png: mark1passwordPng,
    webp112: mark1passwordWebp112,
    webp56: mark1passwordWebp56,
  },
  "ap-mini": { png: apMiniPng, webp112: apMiniWebp112, webp56: apMiniWebp56 },
  "ap-phone": {
    png: apPhonePng,
    webp112: apPhoneWebp112,
    webp56: apPhoneWebp56,
  },
  "ap-plus": { png: apPlusPng, webp112: apPlusWebp112, webp56: apPlusWebp56 },
  "ap-pro": { png: apProPng, webp112: apProWebp112, webp56: apProWebp56 },
  applehealth: {
    png: applehealthPng,
    webp112: applehealthWebp112,
    webp56: applehealthWebp56,
  },
  calendar: {
    png: calendarPng,
    webp112: calendarWebp112,
    webp56: calendarWebp56,
  },
  chatgpt: { png: chatgptPng, webp112: chatgptWebp112, webp56: chatgptWebp56 },
  "chatgpt-atlas": {
    png: chatgptAtlasPng,
    webp112: chatgptAtlasWebp112,
    webp56: chatgptAtlasWebp56,
  },
  chrome: { png: chromePng, webp112: chromeWebp112, webp56: chromeWebp56 },
  claude: { svg: claudeSvg },
  codex: { png: codexPng, webp112: codexWebp112, webp56: codexWebp56 },
  contacts: {
    png: contactsPng,
    webp112: contactsWebp112,
    webp56: contactsWebp56,
  },
  gmail: { png: gmailPng, webp112: gmailWebp112, webp56: gmailWebp56 },
  googlecalendar: {
    png: googlecalendarPng,
    webp112: googlecalendarWebp112,
    webp56: googlecalendarWebp56,
  },
  googledrive: {
    png: googledrivePng,
    webp112: googledriveWebp112,
    webp56: googledriveWebp56,
  },
  granola: { png: granolaPng, webp112: granolaWebp112, webp56: granolaWebp56 },
  instagram: {
    png: instagramPng,
    webp112: instagramWebp112,
    webp56: instagramWebp56,
  },
  lexar: { png: lexarPng, webp112: lexarWebp112, webp56: lexarWebp56 },
  linkedin: {
    png: linkedinPng,
    webp112: linkedinWebp112,
    webp56: linkedinWebp56,
  },
  mercury: { png: mercuryPng, webp112: mercuryWebp112, webp56: mercuryWebp56 },
  messages: {
    png: messagesPng,
    webp112: messagesWebp112,
    webp56: messagesWebp56,
  },
  notes: { png: notesPng, webp112: notesWebp112, webp56: notesWebp56 },
  obsidian: {
    png: obsidianPng,
    webp112: obsidianWebp112,
    webp56: obsidianWebp56,
  },
  safari: { png: safariPng, webp112: safariWebp112, webp56: safariWebp56 },
  spotify: { png: spotifyPng, webp112: spotifyWebp112, webp56: spotifyWebp56 },
  stripe: { png: stripePng, webp112: stripeWebp112, webp56: stripeWebp56 },
  tailscale: {
    png: tailscalePng,
    webp112: tailscaleWebp112,
    webp56: tailscaleWebp56,
  },
  voicememos: {
    png: voicememosPng,
    webp112: voicememosWebp112,
    webp56: voicememosWebp56,
  },
  whatsapp: {
    png: whatsappPng,
    webp112: whatsappWebp112,
    webp56: whatsappWebp56,
  },
} as const;
