/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/editorial.ts
 * Command: astryx theme build src/themes/editorial.ts --out src/themes/editorial.generated.css
 * CLI: @astryxdesign/cli@0.4.6
 * Core: @astryxdesign/core@0.4.6
 */

/// <reference path="./editorial.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const editorialTheme: DefinedTheme;
