/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/life.ts
 * Command: astryx theme build src/themes/life.ts --out src/themes/life.generated.css
 * CLI: @astryxdesign/cli@0.4.6
 * Core: @astryxdesign/core@0.4.6
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
